console.log("My First Console Project");
var first_name="Azhar";
console.log(first_name);
var last_name="Abdulaziz";
console.log(last_name);
var full_name=first_name.concat(last_name);
console.log(full_name);
var a = 5;
var b = 10;
var power=Math.pow(b, a);
console.log(power);
var add = a + b;
console.log(add);